name: Build Libs

on:
  workflow_dispatch:

env:
  SDL_VERSION: release-3.4.16

jobs:
  Build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: win-x64
            lib: SDL3.dll
            platform_args: -DSDL_VULKAN:BOOL=OFF
            strip_args: ""
          - os: macos-latest
            target: osx-arm64
            lib: libSDL3.dylib
            platform_args: -DCMAKE_OSX_ARCHITECTURES=arm64 -DSDL_VULKAN:BOOL=OFF
            strip_args: -x
          - os: macos-latest
            target: osx-x64
            lib: libSDL3.dylib
            platform_args: -DCMAKE_OSX_ARCHITECTURES=x86_64 -DSDL_VULKAN:BOOL=OFF
            strip_args: -x
          - os: ubuntu-latest
            target: linux-x64
            lib: libSDL3.so
            platform_args: -DSDL_KMSDRM=OFF -DSDL_RPI=OFF -DSDL_ROCKCHIP=OFF -DSDL_LIBURING=OFF
            strip_args: --strip-unneeded
    runs-on: ${{matrix.os}}
    steps:
      - name: Clone SDL3
        run: git clone --depth 1 --branch ${{env.SDL_VERSION}} https://github.com/libsdl-org/sdl sdl3-src
      - name: Setup Linux dependencies
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install build-essential git make \
            pkg-config cmake ninja-build gnome-desktop-testing libfribidi-dev libx11-dev libxext-dev \
            libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev \
            libxkbcommon-dev libdbus-1-dev libibus-1.0-dev libudev-dev libthai-dev \
            libwayland-dev libdecor-0-dev
      - name: Build SDL3
        shell: bash
        run: |
          cmake -B build -S sdl3-src \
            -DCMAKE_BUILD_TYPE=Release \
            -DSDL_TEST_LIBRARY=OFF \
            -DSDL_SHARED=ON \
            -DSDL_STATIC=OFF \
            -DSDL_AUDIO=OFF \
            -DSDL_RENDER=OFF \
            -DSDL_CAMERA=OFF \
            -DSDL_HAPTIC=OFF \
            -DSDL_POWER=OFF \
            -DSDL_SENSOR=OFF \
            -DSDL_TRAY=OFF \
            -DSDL_OPENGL=OFF \
            -DSDL_OPENGLES=OFF \
            -DSDL_DUMMYVIDEO=OFF \
            -DSDL_OFFSCREEN=ON \
            -DSDL_VIRTUAL_JOYSTICK=OFF \
            ${{matrix.platform_args}}
          cmake --build build --config Release
      - name: Collect Artifact
        shell: bash
        run: |
          find build -name "${{matrix.lib}}" -exec cp {} . \;
          if [[ -n "${{matrix.strip_args}}" ]]; then
            strip ${{matrix.strip_args}} "${{matrix.lib}}"
          fi
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.target}}
          path: ${{matrix.lib}}
  UpdateLibs:
    if: github.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download libs
        uses: actions/download-artifact@v4
        with:
          path: Framework/Internal/Native
      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.3
        with:
          message: Updated native libs
          committer_name: GitHub Actions
          committer_email: actions@github.com
